spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/gojohnny_db'
    username: 'postgres'
    password: 'postgres'
  jpa:
    properties:
      hibernate:
#        hbm2ddl: {auto: 'create'}
        jdbc: {lob: {non_contextual_creation: true}}
    database-platform: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
  flyway:
    enabled: false