spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        hbm2ddl: {auto: 'create-drop'}
        jdbc: {lob: {non_contextual_creation: true}}
    database-platform: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
  flyway:
    enabled: true